version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR with ACCOUNT ID - $AWS_ACCOUNT_ID AND REGION - $AWS_DEFAULT_REGION...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 336156577369.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Building application jar...
      - ./gradlew clean build
      - echo Building the Docker image...
      - docker build -t valens-helloworld .
      - docker tag valens-helloworld:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/valens-helloworld:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/valens-helloworld:latest
